// Broad configuration settings
.const BACKGROUND_COLOR = BLACK
.const FOREGROUND_COLOR = GREY
.const SUCCESS_COLOR = GREEN
.const FAILURE_COLOR = RED
.const TITLE_COLOR = WHITE
.const NAME_COLOR = LIGHT_GREY
.const DESC_COLOR = LIGHT_BLUE
.const TESTS_PER_PAGE = 21
	
TEST_SUCCESS:
	.byte $73, $00
	
TEST_FAILURE:
	.byte $76, $00
