.const BACKGROUND_COLOR = BLACK
.const FOREGROUND_COLOR = GREY
.const SUCCESS_COLOR = LIGHT_GREEN
.const FAILURE_COLOR = LIGHT_RED
.const TITLE_COLOR = WHITE

TEST_SUCCESS:
	.byte $73, $00
	
TEST_FAILURE:
	.byte $76, $00
	
	
